moment.lang 'en',
  relativeTime:
    future: "in %s"
    past:   "%s"
    s:      "%ds"
    m:      "%dm"
    mm:     "%dm"
    h:      "%dh"
    hh:     "%dh"
    d:      "%dd"
    dd:     "%dd"
    M:      "%dm"
    MM:     "%dm"
    y:      "%dy"
    yy:     "%dy"
